title: Pau Ballada
short_title: PB
email:
description: >-
  Essays on Apple development, AI products, developer tools, and building software with taste.
baseurl: ""
url: https://www.pauballada.com
github_username: pballada
author: Pau Ballada

twitter_username: pballada
show_excerpts: true
google_analytics: G-Z5EE305RXY

theme: minima
plugins:
  - jekyll-feed
